apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: external-federation
spec:
  type: graphql
  lifecycle: production
  owner: engineering
  system: platform
  definition: |
    type Artist {
      id: ID!
      name: String!
      genres: [String!]
    }

    type Query {
      artists(filter: ArtistFilter): [Artist!]!
    }

    input ArtistFilter {
      name: String
    }
